### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by iasoon** [Procrat/eva#7]
## Rationale
Through the course of a day, I tend to get a lot of stimuli. A friend asks me something, I receive an email, I stumble upon something interesting on the internet, suddenly I get inspired and an idea starts developing in my mind, and so on.
For the wannabe-productive-person that I am, this is very annoying, because it takes my attention away from the thing I should be doing. The solution GTD suggests is throwing all these stimuli in a _collection bucket_, to which you get back later for processing (how do I help my friend out with this? Should I act on this email? Is this paper I found really relevant to me? Is this idea any good, and should I develop it further?) . I am very fond of this concept, and would very much like to have it in Eva.
However, currently, it does not really fit, since we only have the concept of tasks, and these are not tasks, but things that _might_ become a task. So, what are they?

I say 'documents'.

## Documents?
A document is like a file on your computer. It can be a blog post, a paper, a web page, a note you wrote, an email, a movie, an image, a documentary, ...
You can think of a document as _an indivisible unit of information_. Here, indivisible means that it cannot be split without taking away information. A book that covers multiple topics could be split in a series of chapters that each cover their own topic, but you take away their context. So, the book is the document, not the chapter. This does, of course, not prevent you from making a part of a a book its own document, provided you are not interested in the other parts. 

### Documents are actionable

Some examples:
- **A paper**
  - Read it.
- **An email**
  - Perform the task that it calls for.
  - Reply to it.
- **A note**
  - Describing a task
    - Do it.
  - Describing an idea
    - Develop the idea.
    - Split it into actionable parts.

In the case a document is not actionable, it does not belong in your task list. You could still archive it, though.

### Documents can be archived
When you decide not to action an idea, you can still choose to archive it. In case you have a new idea that relates to an old one you had, you'd still have your old notes. When you want to try something new and remember that paper you once stumbled upon but didn't read properly, you will still have it. Eva can keep everything safe for you. When you add a tagging system to your archive (which can be 100% the same tagging system as you use for your tasks, so no extra complexity there) it gets easy to use as well!

### Documents are tasks that you did not commit to
I loved @Procrat's determination in the statement 'if you do not have a deadline, you do not intend on finishing that task, so it is clutter on your task list'. I totally agree, however, there are tasks that I _maybe_ would like to do. I sometimes have ideas that I really like, but I don't feel I have time for it, or there are more pressing issues in my life. I would still like to keep this idea, of course. So, it is a document!

### Documents can be reviewed
As time goes by, someone who has tons of stupid ideas like I do will drown in a 'maybe' list filled with tons of crap ideas. Or, a more useful person who has many good ideas, but alas not enough time, might not get back to his million dollar idea. The solution to this is incorporating documents in regular reviews, for example using [spaced repetition](https://en.wikipedia.org/wiki/Spaced_repetition) (In that case, you would get reminded of the idea periodically until you decide you are not going to do it, and you archive the idea). To me this sounds like a good solution to the 800-tabs-to-read problem.

### Documents are a personal reference system
If you dutifully let all your stimuli pass through Eva in this way, you are essentially building a hard-copy of the information in your brain, and all information that is connected to it. This means you can't forget anything. It also means that you start building a model of _how you, personally, handle information_. I believe this opens up great possibilities ;-) .

## How should documents be integrated in Eva?
[I might be wrong](https://www.youtube.com/watch?v=vOa--Dhu11M), but I am starting to believe that documents should be first-class citizens in a personal assistant software. More precisely, they should be _the_ first-class citizen.

### A documents-first approach
Managing time in the information era largely comes down to managing information. Getting a grip on the never-ending information stream that enters our head every day is the first step to making room for productive endeavours. 
By capturing all stimuli you experience and produce into documents, and filing those in your personal organization software, you move the part humans are not good at (managing huge amounts of something) to your computer, while you can focus at the things humans are good at (creating, interacting with the real world, enjoying your life).
A task is, essentially, a document. It's a piece of information that can be actioned. In other words, a task is a scheduled document.
So, approach it like documents. Your 'inbox' is a list of documents that you can either schedule or archive. (You could also include a 'snooze' option, which is the 'maybe / some day' list).

### The far future
For this system to work optimally, you would want it to both collect as much information as possible, and present you with the least work possible.
The first part is achievable by using smart, contextual capture methods (have a browser plugin that sends a link to Eva instead of opening a new tab, have a github integration that captures issues assigned to you, have templates for your notes, have purpose-specific capture devices for specialized cases).
The second part can be achieved by machine learning techniques. Basic text classification is very easy to do, but yields enormous advantages to the user. You could let Eva guess which action will be taken on each item in your 'inbox'. She could then suggest 'maybe archive this bunch?' 'plan this task?' 'put this on your 'maybe' list?

### But what about my flat tire?
I did not form an opinion about how desirable this is yet, but your flat tire and other mundane tasks can also be fit into this flow. When you notice that your bike has a flat tire, it is just that: _an observation_. A piece of information. Something you can note.

Hey Eva, my bike tire is flat.
_Okay, we will get back to that later. We were designing a poster for lightning talks event._

_sorry I did not proofread I have an exam tomorrow the procrastination is real please excuse any brainfarts I would love to hear what you all think love you xoxoxo_

**Comment by Procrat** [comment]
I subscribe to the idea of making it easy to make a brain dump or information dump in Eva, and then reviewing them at some later stage. It is also interesting to see a completely different view of how most to-do lists tend to work: whereas they normally let you list "solutions", you propose to list "problems". Did I interpret that right?

At the moment, I'm not sure how to think about this, neither as a user nor as a developer. The main question that interests me is how would you like to interact with a document-centric Eva (given a reasonable amount of developer time)?

**Comment by Procrat** [comment]
I recently came across an interesting app called [moo.do](https://www.moo.do) that takes emails and Google Drive documents (and possibly other things as well) as first-class citizens. It might interest you.
